name: example
description: An example Flutter project to demonstrate the usage of cached_build_runner.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  json_serializable: ^6.9.5
  json_annotation: ^4.9.0
  freezed_annotation: ^3.0.0
  auto_mappr_annotation: ^2.3.0

dev_dependencies:
  build_runner: ^2.4.15
  cached_build_runner:
    path: ../
  auto_mappr: ^2.8.1

  flutter_lints: ^5.0.0
  freezed: ^3.0.6

flutter:
  uses-material-design: true
